
require 'rqrcode'
require 'webpush'
require 'paho-mqtt'
require 'redis-objects'
require 'sinatra/base'
#require 'sinatra-websocket'
require 'thin'
require 'json'
require 'slop'
require 'pry'
require 'rufus-scheduler'
require 'twilio-ruby'
require 'redcarpet'
require 'cerebrum'
require 'cryptology'
require 'sentimental'
require 'digest/md5'
require 'securerandom'
require 'browser'
require 'faraday'

load "bin/colorize.rb"
