# network wide configuration.                                                                                                                            
# this is te server we connect to for telemetry and communications.                                                                                      
export CLUSTER='localhost';                                                                                                                              
export NICK='nomad';
# certbot registration email.
export EMAIL='';                                                                                                                                     
# the first domain indomains or the renewed certificate generated by certbot.                                                                                                        
export DOMAIN_ROOT='';                                                                                                                       
# set to false for cloud (hub) usage.
export BOX='false';
# pre-configure domains for hub
export DOMAINS='';
# the twilio api sid and key used for sms authentication, etc.                                                                                           
export PHONE_SID='';                                                                                                                           
export PHONE_KEY='';
#export GUI="true";
#export BONNET='true';                                                                                                                                   
#export MINE='true';                                                                                                                                     
#export MUSH='true';                                                                                                                                     
#export DEVS='true';     
export PORT_ROOT=8080;
export MUMBLE_ROOT=64738;
export MUMBLE=64738;                                                           
# end of network configuration.                                                                                                                          
#   
# EDIT TO SUIT YOUR NEEDS.
#
export DOMAIN='localhost';
export PHONE='';
export ADMIN='';
export MUMBLE='64738';
export OWNERSHIP='';
export EXCHANGE='';
export SHARES='';
export XFER='';
redis-cli hset PHONES localhost $PHONE > /dev/null; 
redis-cli hset MUMBLE localhost $MUMBLE > /dev/null;
redis-cli hset ADMINS localhost $ADMIN > /dev/null;
redis-cli hset OWNERSHIP localhost $OWNERSHIP > /dev/null;
redis-cli hset EXCHANGE localhost $EXCHANGE > /dev/null; 
redis-cli hset SHARES localhost $SHARES > /dev/null;
redis-cli hset XFER localhost $XFER > /dev/null;
ruby bin/mumble.rb localhost;
umurmurd -c mumble/$DOMAIN.conf
